services:
  db:
    image: postgis/postgis:16-3.4
    container_name: faune_flore_postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: faune_flore
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  gdal:
    build:
      context: .
      dockerfile: Dockerfile.gdal
    container_name: gdal_tools
    volumes:
      - ./data:/data
    entrypoint: ["/bin/bash", "-lc", "sleep infinity"]
